"use client";
import { useEffect } from "react";
import { initMixpanel, trackPageView } from "@/lib/mixpanel";

export default function TermsOfService() {
  useEffect(() => {
    initMixpanel();
    trackPageView('Terms of Service');
  }, []);

  return (
    <div className="min-h-screen bg-neutral-950 text-white font-sans p-6 md:p-12">
      <div className="max-w-3xl mx-auto space-y-8">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-indigo-400">Agreemement to Terms</h2>
          <p className="text-gray-300 leading-relaxed">
            By accessing or using Neural TTS, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-indigo-400">Use License</h2>
          <p className="text-gray-300">
             Permission is granted to temporarily download the materials (information or software) on Neural TTS's website for personal, non-commercial transitory viewing only.
          </p>
          <p className="text-gray-300">
             The audio files generated by our service are yours to use, subject to the rights of the underlying voice providers. Generally, these are free for personal and commercial use, but you are responsible for verifying compliance with the source providers.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-indigo-400">Disclaimer</h2>
          <p className="text-gray-300">
            The materials on Neural TTS's website are provided on an 'as is' basis. Neural TTS makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
          </p>
        </section>
        
         <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-indigo-400">Limitations</h2>
          <p className="text-gray-300">
             In no event shall Neural TTS or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Neural TTS's website.
          </p>
        </section>

        <div className="mt-12 pt-8 border-t border-white/10">
          <a href="/" className="text-indigo-400 hover:text-indigo-300 transition-colors">← Back to Home</a>
        </div>
      </div>
    </div>
  );
}
